// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNNvSXCA5GvzotGwPkgEX_4VHoKmbSyfY',
    appId: '1:659671107098:web:83673dc1235685512fb3a3',
    messagingSenderId: '659671107098',
    projectId: 'mochamind-92ac3',
    authDomain: 'mochamind-92ac3.firebaseapp.com',
    storageBucket: 'mochamind-92ac3.firebasestorage.app',
    measurementId: 'G-N2G01VS5MW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcYw5AB31ogKNZcV0obH8IHtz3EXI-Zuc',
    appId: '1:659671107098:android:928a7d597309b3d42fb3a3',
    messagingSenderId: '659671107098',
    projectId: 'mochamind-92ac3',
    storageBucket: 'mochamind-92ac3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbLudUCyjE52f5nx3XrZ1PVmcrsFrYVBU',
    appId: '1:659671107098:ios:e9448a9d611059502fb3a3',
    messagingSenderId: '659671107098',
    projectId: 'mochamind-92ac3',
    storageBucket: 'mochamind-92ac3.firebasestorage.app',
    iosClientId: '659671107098-e8c6ddbalhbvnob3ieohurogmg18cfpb.apps.googleusercontent.com',
    iosBundleId: 'com.mochamind.mochamind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbLudUCyjE52f5nx3XrZ1PVmcrsFrYVBU',
    appId: '1:659671107098:ios:e9448a9d611059502fb3a3',
    messagingSenderId: '659671107098',
    projectId: 'mochamind-92ac3',
    storageBucket: 'mochamind-92ac3.firebasestorage.app',
    iosClientId: '659671107098-e8c6ddbalhbvnob3ieohurogmg18cfpb.apps.googleusercontent.com',
    iosBundleId: 'com.mochamind.mochamind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNNvSXCA5GvzotGwPkgEX_4VHoKmbSyfY',
    appId: '1:659671107098:web:c177cf9e6ed86a972fb3a3',
    messagingSenderId: '659671107098',
    projectId: 'mochamind-92ac3',
    authDomain: 'mochamind-92ac3.firebaseapp.com',
    storageBucket: 'mochamind-92ac3.firebasestorage.app',
    measurementId: 'G-9LS2FWGLPT',
  );
}
